server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址
        server-addr: 192.168.26.128:1111 #配置lunix中的nginx的1111端口转发到Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

